export const TASK_ACTIVITY_TYPES = {
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_MOVED: "TASK_MOVED",
  COMMENT_CREATED: "COMMENT_CREATED",
  COMMENT_DELETED: "COMMENT_DELETED",
  FILE_UPLOADED: "FILE_UPLOADED",
  FILE_DELETED: "FILE_DELETED",
  APPROVAL_REQUESTED: "APPROVAL_REQUESTED",
  TASK_APPROVED: "TASK_APPROVED",
  CHANGES_REQUESTED: "CHANGES_REQUESTED",
  PORTAL_COMMENT_CREATED: "PORTAL_COMMENT_CREATED",
  PORTAL_TASK_APPROVED: "PORTAL_TASK_APPROVED",
  PORTAL_CHANGES_REQUESTED: "PORTAL_CHANGES_REQUESTED",
  TIME_STARTED: "TIME_STARTED",
  TIME_STOPPED: "TIME_STOPPED",
  TIME_MANUAL_CREATED: "TIME_MANUAL_CREATED",
  TIME_ENTRY_UPDATED: "TIME_ENTRY_UPDATED",
  TIME_ENTRY_DELETED: "TIME_ENTRY_DELETED",
} as const;

export type TaskActivityType =
  (typeof TASK_ACTIVITY_TYPES)[keyof typeof TASK_ACTIVITY_TYPES];
